name: 'Dependabot Auto-Merge'

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.0
        with:
          target: minor
          github-token: ${{ secrets.token }}
